version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: symshopev2
      # You should definitely change the password in production
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
      ###< doctrine/doctrine-bundle ###
    ports:
      - '127.0.0.1:5434:5432'

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data: ###< doctrine/doctrine-bundle ###
