# test:
#   path: /test/{age<\d+>?-1}
#   controller: App\Controller\TestController::test
#   methods: [POST, GET]
#   host: 127.0.0.1
#   schemes: [https, http]
#   # defaults:
#   #   age: -1
#   # requirements:
#   #   age: \d+
