# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    stripe_secret_key: sk_test_51KXlDaHaSfa42x4ZIMedqAm9dfs8hKwv0XLBxUpWMcaHFChurlUrk0K7sKhAcAajROrSuUO4M66ghajHSxnYFt5W00DBKhz0io
    stripe_public_key: pk_test_51KXlDaHaSfa42x4ZDb9Dd7JYCcQCpl38zWGUkBm7704dz7Xfu219xiLsJYdnaWt9YIzQJGvOZtp8mLbVmm041s1p00QQatZQz2

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
            - "../src/Tests/"

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: "../src/Controller/"
        tags: ["controller.service_arguments"]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Taxes\Caculator:
        arguments:
            $tva: 20
    App\Taxes\Detector:
        arguments:
            $seuil: 100

    Cocur\Slugify\Slugify: ~
